package org.yalli.wah.model.enums;

public enum MentorCategory {
    EDUCATION_AND_ACADEMIC_SUPPORT,
    CAREER_AND_BUSINESS,
    PERSONAL_DEVELOPMENT_AND_PSYCHOLOGY,
    TRAVEL_PLANNING_AND_GUIDING,
    VISA_AND_IMMIGRATION_ADVICE,
    ACCOMMODATION_AND_LIVING,
    LAWS
}
