package org.yalli.wah.util;

import org.apache.commons.lang3.RandomStringUtils;
import org.hibernate.validator.internal.xml.mapping.MappingXmlParser;
import org.yalli.wah.model.exception.InvalidInputException;

import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.security.Key;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Random;

public class TranslateUtil {
    private static final String ALPHANUMERICS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    private static  Map<String, String> countryMap = new HashMap<>();
    private static  Map<String, String> cityMap = new HashMap<>();

    static {
        countryMap.put("Türkiyə", "Türkiye");
        countryMap.put("Azərbaycan", "Azerbaijan");
        countryMap.put("Rusiya", "Russia");
        countryMap.put("Almaniya", "Germany");
        countryMap.put("ABŞ", "USA");
        countryMap.put("Ukrayna", "Ukraine");
        countryMap.put("Böyük Britaniya", "United Kingdom");
        countryMap.put("Kanada", "Canada");
        countryMap.put("Fransa", "France");
        countryMap.put("İsrail", "Israel");
        countryMap.put("Gürcüstan", "Georgia");
        countryMap.put("İtaliya", "Italy");
        countryMap.put("Avstraliya", "Australia");
        countryMap.put("İspaniya", "Spain");
        countryMap.put("Niderland", "Netherlands");
        countryMap.put("Avstriya", "Austria");
        countryMap.put("İsveç", "Sweden");
        countryMap.put("Belçika", "Belgium");
        countryMap.put("Norveç", "Norway");
        countryMap.put("Finlandiya", "Finland");
        countryMap.put("Macarıstan", "Hungary");
        countryMap.put("Polşa", "Poland");
        countryMap.put("Yunanıstan", "Greece");
        countryMap.put("Slovakiya", "Slovakia");
        countryMap.put("Litva", "Lithuania");
        countryMap.put("Latviya", "Latvia");
        countryMap.put("Estoniya", "Estonia");
        countryMap.put("Qazaxıstan", "Kazakhstan");
        countryMap.put("BƏƏ", "UAE");
        countryMap.put("Yaponiya", "Japan");
        countryMap.put("İran", "Iran");
        countryMap.put("Səudiyyə Ərəbistanı", "Saudi Arabia");
        countryMap.put("Belarus", "Belarus");
        countryMap.put("Moldova", "Moldova");
        countryMap.put("Qırğızıstan", "Kyrgyzstan");
        countryMap.put("Tacikistan", "Tajikistan");
        countryMap.put("Türkmənistan", "Turkmenistan");
        countryMap.put("Özbəkistan", "Uzbekistan");
        countryMap.put("Malayziya", "Malaysia");
        countryMap.put("Sinqapur", "Singapore");
        countryMap.put("Braziliya", "Brazil");
        countryMap.put("Argentina", "Argentina");
        countryMap.put("Meksika", "Mexico");
        countryMap.put("Vietnam", "Vietnam");
        countryMap.put("Bali (İndoneziya)", "Bali (Indonesia)");
        countryMap.put("İsveçrə", "Switzerland");
        countryMap.put("Portuqaliya", "Portugal");
        countryMap.put("Cənubi Koreya", "South Korea");

    }

    static{
        cityMap.put("Gimhe", "Gimhae");
        cityMap.put("Çincu", "Jinju");
        cityMap.put("İksan", "Iksan");
        cityMap.put("Yancu", "Yangju");
        cityMap.put("Asan", "Asan");
        cityMap.put("Andon", "Andong");
        cityMap.put("Toneyon", "Tongyeong");
        cityMap.put("Sokço", "Sokcho");
        cityMap.put("Pacu", "Paju");
        cityMap.put("Kvanmyeon", "Gwangmyeong");
        cityMap.put("Ansan", "Ansan");
        cityMap.put("Sancu Quanavato", "Sangju Guanajuato");
        cityMap.put("İrapuato", "Irapuato");
        cityMap.put("San Andres Tustla", "San Andrés Tuxtla");
        cityMap.put("Guasave", "Guasave");
        cityMap.put("Puerto de Proqreso", "Puerto de Progreso");
        cityMap.put("Amekameka", "Amecameca");
        cityMap.put("Cholula", "Cholula");
        cityMap.put("Tapaçula", "Tapachula");
        cityMap.put("Metepek", "Metepec");
        cityMap.put("Tepeci del Rio", "Tepeji del Río");
        cityMap.put("Atlixko", "Atlixco");
        cityMap.put("Mişoakan", "Michoacán (State)");
        cityMap.put("Verakrus-Boka del Rio", "Veracruz-Boca del Río");
        cityMap.put("Xalisko", "Jalisco (State)");
        cityMap.put("Kuliakan Rosales", "Culiacán Rosales");
        cityMap.put("Baxa Kaliforniya", "Baja California (State)");
        cityMap.put("Nuevo Leon", "Nuevo León (State)");
        cityMap.put("Sonora", "Sonora (State)");
        cityMap.put("Kampeçe", "Campeche (State)");
        cityMap.put("Quanavato", "Guanajuato (State)");
        cityMap.put("Sinaloa", "Sinaloa (State)");
        cityMap.put("Koahuila", "Coahuila (State)");
        cityMap.put("Aquaskalientes", "Aguascalientes (State)");
        cityMap.put("Oaxaca de Huares", "Oaxaca de Juárez");
        cityMap.put("Monklova", "Monclova");
        cityMap.put("Navoxoa", "Navojoa");
        cityMap.put("Paçuka de Soto", "Pachuca de Soto");
        cityMap.put("Tamaulipas", "Tamaulipas (State)");
        cityMap.put("Boka del Rio", "Boca del Río");
        cityMap.put("Çihuahua Şəhəri", "Chihuahua City");
        cityMap.put("Mazatlan", "Mazatlán");
        cityMap.put("Hanoy", "Hanoi");
        cityMap.put("Ho Chi Minh Şəhəri", "Ho Chi Minh City");
        cityMap.put("Da Nanq", "Da Nang");
        cityMap.put("Hay Fonq", "Hai Phong");
        cityMap.put("Kan Tho", "Can Tho");
        cityMap.put("Bien Hoa", "Bien Hoa");
        cityMap.put("Nha Tranq", "Nha Trang");
        cityMap.put("Hue", "Hue");
        cityMap.put("Vin", "Vinh");
        cityMap.put("Fan Tiet", "Phan Thiết");
        cityMap.put("Raç Gia", "Rach Gia");
        cityMap.put("Bak Lieu", "Bac Lieu");
        cityMap.put("Tuy Hoa", "Tuy Hoa");
        cityMap.put("Quy Nhon", "Quy Nhon");
        cityMap.put("Nam Din", "Nam Dinh");
        cityMap.put("Ben Tre", "Ben Tre");
        cityMap.put("Vunq Tau", "Vung Tau");
        cityMap.put("Phu Quoc", "Phu Quoc");
        cityMap.put("Ha Lonq", "Ha Long");
        cityMap.put("Son Tay", "Son Tay");
        cityMap.put("Lonq Xuyen", "Long Xuyen");
        cityMap.put("Mı Tho", "My Tho");
        cityMap.put("Hay Dıonq", "Hai Duong");
        cityMap.put("Tam Kı", "Tam Ky");
        cityMap.put("Lao Kay", "Lao Cai");
        cityMap.put("Kon Tum", "Kon Tum");
        cityMap.put("Quang Ngay", "Quang Ngai");
        cityMap.put("Bak Zianq", "Bac Giang");
        cityMap.put("Nin Bin", "Ninh Binh");
        cityMap.put("Ka Mau", "Ca Mau");
        cityMap.put("Yen Bay", "Yen Bai");
        cityMap.put("Tan Hoa", "Thanh Hoa");
        cityMap.put("Quang Nin", "Quang Ninh");
        cityMap.put("Tan An", "Tan An");
        cityMap.put("Phu Yen", "Phu Yen");
        cityMap.put("Da Lat", "Da Lat");
        cityMap.put("Sonq Kau", "Song Cau");
        cityMap.put("Bak Nin", "Bac Ninh");
        cityMap.put("Kam Pha", "Cam Pha");
        cityMap.put("Lanq Son", "Lang Son");
        cityMap.put("Hoa Bin", "Hoa Binh");
        cityMap.put("Vin Lonq", "Vinh Long");
        cityMap.put("Bao Lok", "Bao Loc");
        cityMap.put("Monq Kay", "Mong Cai");
        cityMap.put("Tra Vin", "Tra Vinh");
        cityMap.put("Vin Yen", "Vinh Yen");
        cityMap.put("Quang Tri", "Quang Tri");
        cityMap.put("Donq Xoay", "Dong Xoai");
        cityMap.put("Khanh Hoa", "Khanh Hoa (Province)");
        cityMap.put("Bin Phuok", "Binh Phuoc (Province)");
        cityMap.put("Dien Bien Phu", "Dien Bien Phu");
        cityMap.put("An Zianq", "An Giang (Province)");
        cityMap.put("Kao Banq", "Cao Bang (Province)");
        cityMap.put("Tuyen Quang", "Tuyen Quang (Province)");
        cityMap.put("Lay Çau", "Lai Chau (Province)");
        cityMap.put("Quang Bin", "Quang Binh (Province)");
        cityMap.put("Tay Nguyen", "Thai Nguyen (Province)");
        cityMap.put("Phu Tho", "Phu Tho (Province)");
        cityMap.put("Hunq Yen", "Hung Yen (Province)");
        cityMap.put("Hay Fonq", "Hai Phong (Province - Duplicated city name)");
        cityMap.put("Bin Dıonq", "Binh Duong (Province)");
        cityMap.put("Donq Nai", "Dong Nai (Province)");
        cityMap.put("Kan Tho", "Can Tho (Province - Duplicated city name)");
        cityMap.put("Kien Zianq", "Kien Giang (Province)");
        cityMap.put("Bak Kan", "Bac Kan (Province)");
        cityMap.put("Bin Din", "Binh Dinh (Province)");
        cityMap.put("Quang Nam", "Quang Nam (Province)");
        cityMap.put("Tay Bin", "Thai Binh (Province)");
        cityMap.put("Ha Tin", "Ha Tinh (Province)");
        cityMap.put("Son La", "Son La (Province)");
        cityMap.put("Bin Tuan", "Binh Thuan (Province)");
        cityMap.put("Tua Tien Hue", "Thua Thien Hue (Province)");
        cityMap.put("Dak Lak", "Dak Lak (Province)");
        cityMap.put("Gia Lay", "Gia Lai (Province)");
        cityMap.put("Sayqon", "Saigon (Ho Chi Minh City)");
        cityMap.put("Dak Nonq", "Dak Nong (Province)");
        cityMap.put("Ha Nam", "Ha Nam (Province)");
        cityMap.put("Vin Fuk", "Vinh Phuc (Province)");
        cityMap.put("Lonq An", "Long An (Province)");
        cityMap.put("Quang Ngay", "Quang Ngai (Province - Duplicated city name)");
        cityMap.put("Bak Kan", "Bac Kan (Province - Duplicated city name)");
        cityMap.put("Denpasar", "Denpasar");
        cityMap.put("Ubud", "Ubud");
        cityMap.put("Kuta", "Kuta");
        cityMap.put("Seminyak", "Seminyak");
        cityMap.put("Canqqu", "Canggu");
        cityMap.put("Sanur", "Sanur");
        cityMap.put("Nusa Dua", "Nusa Dua");
        cityMap.put("Cimbaran", "Jimbaran");
        cityMap.put("Tabanan", "Tabanan");
        cityMap.put("Amplura", "Amlapura");
        cityMap.put("Klunqkunq", "Klungkung");
        cityMap.put("Banqli", "Bangli");
        cityMap.put("Bulelenq", "Buleleng");
        cityMap.put("Karanqasem", "Karangasem");
        cityMap.put("Tampak Sirinq", "Tampaksiring");
        cityMap.put("Beduqul", "Bedugul");
        cityMap.put("Sinqaraca", "Singaraja");
        cityMap.put("Uluwatu", "Uluwatu");
        cityMap.put("Binqin", "Bingin");
        cityMap.put("Lovina", "Lovina");
        cityMap.put("Bern", "Bern");
        cityMap.put("Zürih", "Zürich");
        cityMap.put("Cenevre", "Geneva");
        cityMap.put("Bazel", "Basel");
        cityMap.put("Lozan", "Lausanne");
        cityMap.put("Lusern", "Lucerne");
        cityMap.put("İnterlaken", "Interlaken");
        cityMap.put("St Moritz", "St. Moritz");
        cityMap.put("Lozanna", "Lausanne (Duplicated city name)");
        cityMap.put("Luqano", "Lugano");
        cityMap.put("Vintertur", "Winterthur");
        cityMap.put("Tun", "Thun");
        cityMap.put("Neuşatel", "Neuchâtel");
        cityMap.put("Friburq", "Fribourg");
        cityMap.put("Arau", "Aarau");
        cityMap.put("Çur", "Chur");
        cityMap.put("Sion", "Sion");
        cityMap.put("Soloturn", "Solothurn");
        cityMap.put("Biel/Bien", "Biel/Bienne");
        cityMap.put("St Gallen", "St. Gallen");
        cityMap.put("Lusern", "Lucerne (Duplicated city name)");
        cityMap.put("Zuq", "Zug");
        cityMap.put("Şafhauzen", "Schaffhausen");
        cityMap.put("Liestal", "Liestal");
        cityMap.put("Rappersvil-Yona", "Rapperswil-Jona");
        cityMap.put("Monte", "Monthey");
        cityMap.put("Olten", "Olten");
        cityMap.put("Aarqau", "Aargau (Region)");
        cityMap.put("Lanqental", "Langenthal");
        cityMap.put("Zürih Kanton", "Zurich Canton (Canton)");
        cityMap.put("Cenevre Kanton", "Geneva Canton (Canton)");
        cityMap.put("Appenzell", "Appenzell (Canton)");
        cityMap.put("Emmental", "Emmental (Region)");
        cityMap.put("Biel", "Biel (Duplicated city name)");
        cityMap.put("Porrentruy", "Porrentruy");
        cityMap.put("Lissabon", "Lisbon");
        cityMap.put("Porto", "Porto");
        cityMap.put("Amadora", "Amadora");
        cityMap.put("Braqa", "Braga");
        cityMap.put("Koimbra", "Coimbra");
        cityMap.put("Funçal", "Funchal");
        cityMap.put("Evora", "Evora");
        cityMap.put("Kaskais", "Cascais");
        cityMap.put("Almada", "Almada");
        cityMap.put("Aveiro", "Aveiro");
        cityMap.put("Leiria", "Leiria");
        cityMap.put("Vila Nova de Gaia", "Vila Nova de Gaia");
        cityMap.put("Vizeu", "Viseu");
        cityMap.put("Santarem", "Santarém");
        cityMap.put("Braqansa", "Bragança");
        cityMap.put("Setubal", "Setúbal");
        cityMap.put("Viana do Kastelo", "Viana do Castelo");
        cityMap.put("Evora", "Évora (Duplicated city name)");
        cityMap.put("Oeiras", "Oeiras");
        cityMap.put("Barselos", "Barcelos");
        cityMap.put("Ponta Delqada", "Ponta Delgada");
        cityMap.put("Quimaraeş", "Guimarães");
        cityMap.put("Maia", "Maia");
        cityMap.put("Ovar", "Ovar");
        cityMap.put("Faro", "Faro");
        cityMap.put("Matosinos", "Matosinhos");
        cityMap.put("Celorico da Beira", "Celorico da Beira");
        cityMap.put("Tavira", "Tavira");
        cityMap.put("Tondela", "Tondela");
        cityMap.put("Sintra", "Sintra");
        cityMap.put("Povoa de Varzim", "Póvoa de Varzim");
        cityMap.put("Batalha", "Batalha");
        cityMap.put("Seyşal", "Seixal");
        cityMap.put("Montixo", "Montijo");
        cityMap.put("Anqra do Heroismo", "Angra do Heroísmo");
        cityMap.put("Santa Maria da Feira", "Santa Maria da Feira");
        cityMap.put("Espozende", "Esposende");
        cityMap.put("Penafiel", "Penafiel");
        cityMap.put("Albufeira", "Albufeira");
        cityMap.put("Marinya Grande", "Marinha Grande");
        cityMap.put("Seul", "Seoul");
        cityMap.put("Busan", "Busan");
        cityMap.put("İnçon", "Incheon");
        cityMap.put("Tequ", "Daegu");
        cityMap.put("Tecon", "Daejeon");
        cityMap.put("Kvanju", "Gwangju");
        cityMap.put("Ulsan", "Ulsan");
        cityMap.put("Suvon", "Suwon");
        cityMap.put("Çanqvon", "Changwon");
        cityMap.put("Koyanq", "Goyang");
        cityMap.put("Seonqnam", "Seongnam");
        cityMap.put("Buçon", "Bucheon");
        cityMap.put("Çonqju", "Cheongju");
        cityMap.put("Çeonan", "Cheonan");
        cityMap.put("Concu", "Jeonju");
        cityMap.put("Cecu", "Jeju");
        cityMap.put("Kimpo", "Gimpo");
        cityMap.put("Pohanq", "Pohang");
        cityMap.put("Kannın", "Gangneung");
        cityMap.put("Voncu", "Wonju");
        cityMap.put("Yonqgin", "Yongin");
        cityMap.put("Kumi", "Gumi");
        cityMap.put("Miryanq", "Miryang");
        cityMap.put("Samçok", "Samcheok");
        cityMap.put("Çanqsu", "Jangsu");
        cityMap.put("Çanheunq", "Jangheung");
        cityMap.put("Nacu", "Naju");
        cityMap.put("Namyancu", "Namyangju");
        cityMap.put("Pekin", "Beijing");
        cityMap.put("Şanxay", "Shanghai");
        cityMap.put("Çunçin", "Chongqing");
        cityMap.put("Tiancin", "Tianjin");
        cityMap.put("Quanqcou", "Guangzhou");
        cityMap.put("Şencen", "Shenzhen");
        cityMap.put("Çendu", "Chengdu");
        cityMap.put("Si An", "Xi'an");
        cityMap.put("Donqquan", "Dongguan");
        cityMap.put("Hanqcou", "Hangzhou");
        cityMap.put("Nankinq", "Nanjing");
        cityMap.put("Uhan", "Wuhan");
        cityMap.put("Şiciajuanq", "Shijiazhuang");
        cityMap.put("Çonçin", "Chongqing (Duplicated city name)");
        cityMap.put("Harbin", "Harbin");
        cityMap.put("Qindao", "Qingdao");
        cityMap.put("Dalian", "Dalian");
        cityMap.put("Zenczou", "Zhengzhou");
        cityMap.put("Suzhou", "Suzhou");
        cityMap.put("Çanqşa", "Changsha");
        cityMap.put("Cinan", "Jinan");
        cityMap.put("Kunminq", "Kunming");
        cityMap.put("Ninqbo", "Ningbo");
        cityMap.put("Siamen", "Xiamen");
        cityMap.put("Foşan", "Foshan");
        cityMap.put("Loyanq", "Luoyang");
        cityMap.put("Tayyuan", "Taiyuan");
        cityMap.put("Yancou", "Yangzhou");
        cityMap.put("Anşan", "Anshan");
        cityMap.put("Hefei", "Hefei");
        cityMap.put("Lin Yi", "Linyi");
        cityMap.put("Zi Bo", "Zibo");
        cityMap.put("Cianqmen", "Jiangmen");
        cityMap.put("Cianqyin", "Jiangyin");
        cityMap.put("Liao Yanq", "Liaoyang");
        cityMap.put("Bao Tou", "Baotou");
        cityMap.put("Yantai", "Yantai");
        cityMap.put("Şantou", "Shantou");
        cityMap.put("Uşi", "Wuxi");
        cityMap.put("Çanqcou", "Zhangzhou");
        cityMap.put("Nantonq", "Nantong");
        cityMap.put("Çançun", "Changchun");
        cityMap.put("Qi Qi Har", "Qiqihar");
        cityMap.put("Fucou", "Fuzhou");
        cityMap.put("Şaoşinq", "Shaoxing");
        cityMap.put("Bao Din", "Baoding");
        cityMap.put("Tanqşan", "Tangshan");
        cityMap.put("Yancianq", "Yangjiang");
        cityMap.put("Hainan", "Hainan (Province)");
        cityMap.put("Vencou", "Wenzhou");
        cityMap.put("Lianyunqanq", "Lianyungang");
        cityMap.put("Huanqşan", "Huangshan");
        cityMap.put("Çuzhou", "Chuzhou");
        cityMap.put("Liaoçenq", "Liaocheng");
        cityMap.put("Zencianq", "Zhenjiang");
        cityMap.put("Yançenq", "Yancheng");
        cityMap.put("Huanqqanq", "Huanggang");
        cityMap.put("Şuanqyaşan", "Shuangyashan");
        cityMap.put("Veifanq", "Weifang");
        cityMap.put("Dandonq", "Dandong");
        cityMap.put("Dazhou", "Dazhou");
        cityMap.put("Yunnan", "Yunnan (Province)");
        cityMap.put("Çande", "Changde");
        cityMap.put("Huicou", "Huizhou");
        cityMap.put("Luzhou", "Luzhou");
        cityMap.put("Çanciakou", "Zhangjiakou");
        cityMap.put("Deyanq", "Deyang");
        cityMap.put("Lanqfanq", "Langfang");
        cityMap.put("Huanqşi", "Huangshi");
        cityMap.put("Qiancianq", "Qianjiang");
        cityMap.put("Quiyanq", "Guiyang");
        cityMap.put("Cianqsu", "Jiangsu (Province)");
        cityMap.put("Quançou", "Quanzhou");
        cityMap.put("Yueyanq", "Yueyang");
        cityMap.put("Baoşan", "Baoshan");
        cityMap.put("Sinxianq", "Xinxiang");
        cityMap.put("Sipinq", "Siping");
        cityMap.put("Çonqzou", "Chongzuo");
        cityMap.put("Henqyanq", "Hengyang");
        cityMap.put("Cilin", "Jilin (Province)");
        cityMap.put("Rizhao", "Rizhao");
        cityMap.put("Hohhot", "Hohhot");
        cityMap.put("Süzhou", "Xuzhou");
        cityMap.put("Nanyanq", "Nanyang");
        cityMap.put("Ciaxinq", "Jiaxing");
        cityMap.put("Puyanq", "Puyang");
        cityMap.put("Vuhu", "Wuhu");
        cityMap.put("Tianmen", "Tianmen");
        cityMap.put("Lai Vu", "Laiwu");
        cityMap.put("Licianq", "Lijiang");
        cityMap.put("Anhui", "Anhui (Province)");
        cityMap.put("Bankok", "Bangkok");
        cityMap.put("Çianq Mai", "Chiang Mai");
        cityMap.put("Phuket", "Phuket");
        cityMap.put("Pattaya", "Pattaya");
        cityMap.put("Nakon Ratçasima", "Nakhon Ratchasima");
        cityMap.put("Hua Hin", "Hua Hin");
        cityMap.put("Ayutthaya", "Ayutthaya");
        cityMap.put("Çianq Ray", "Chiang Rai");
        cityMap.put("Nakon Si Tammrat", "Nakhon Si Thammarat");
        cityMap.put("Sonqkla", "Songkhla");
        cityMap.put("Rayonq", "Rayong");
        cityMap.put("Krabi", "Krabi");
        cityMap.put("Surat Tani", "Surat Thani");
        cityMap.put("Udon Tani", "Udon Thani");
        cityMap.put("Kon Ken", "Khon Kaen");
        cityMap.put("Loei", "Loei");
        cityMap.put("Nakon Pathom", "Nakhon Pathom");
        cityMap.put("Sukotay", "Sukhothai");
        cityMap.put("Ratçaburi", "Ratchaburi");
        cityMap.put("Tranq", "Trang");
        cityMap.put("Çonburi", "Chonburi");
        cityMap.put("Samut Prakan", "Samut Prakan");
        cityMap.put("Lamphun", "Lamphun");
        cityMap.put("Nakon Savan", "Nakhon Sawan");
        cityMap.put("Sa Kaeo", "Sa Kaeo");
        cityMap.put("Çayaphum", "Chaiyaphum");
        cityMap.put("Petçabun", "Phetchabun");
        cityMap.put("Kançanaburi", "Kanchanaburi");
        cityMap.put("Ubon Ratçatani", "Ubon Ratchathani");
        cityMap.put("Phitsanulok", "Phitsanulok");
        cityMap.put("Sakon Nakon", "Sakon Nakhon");
        cityMap.put("Buriram", "Buriram");
        cityMap.put("Çumphon", "Chumphon");
        cityMap.put("Praçuap Kiri Khan", "Prachuap Khiri Khan");
        cityMap.put("Nonq Kay", "Nong Khai");
        cityMap.put("Nakon Nayok", "Nakhon Nayok");
        cityMap.put("Ranonq", "Ranong");
        cityMap.put("Phrae", "Phrae");
        cityMap.put("Surin", "Surin");
        cityMap.put("Anq Thonq", "Ang Thong");
        cityMap.put("Pathum Tani", "Pathum Thani");
        cityMap.put("Saraburi", "Saraburi");
        cityMap.put("Samut Sakhon", "Samut Sakhon");
        cityMap.put("Mae Honq Son", "Mae Hong Son");
        cityMap.put("Pattani", "Pattani");
        cityMap.put("Yala", "Yala");
        cityMap.put("Satun", "Satun");
        cityMap.put("Roi Et", "Roi Et");
        cityMap.put("Kalasin", "Kalasin");
        cityMap.put("Praçinburi", "Prachinburi");
        cityMap.put("Kair", "Cairo");
        cityMap.put("İskəndəriyyə", "Alexandria");
        cityMap.put("Şarm Əl Şeyx", "Sharm El Sheikh");
        cityMap.put("Hurqada", "Hurghada");
        cityMap.put("Mansura", "Mansoura");
        cityMap.put("Suez", "Suez");
        cityMap.put("Luksor", "Luxor");
        cityMap.put("Qena", "Qena");
        cityMap.put("Asvan", "Aswan");
        cityMap.put("Tanta", "Tanta");
        cityMap.put("Banha", "Banha");
        cityMap.put("Feyyum", "Fayyum");
        cityMap.put("Minya", "Minya");
        cityMap.put("İsmailiyya", "Ismailia");
        cityMap.put("Damanhur", "Damanhur");
        cityMap.put("Kafr Əl Şeyx", "Kafr el-Sheikh");
        cityMap.put("Beni Suef", "Beni Suef");
        cityMap.put("Giza", "Giza");
        cityMap.put("Qalyubiya", "Qalyubia");
        cityMap.put("Şarqiya", "Sharqiya");
        cityMap.put("Əlcəzair Şəhəri", "Algiers");
        cityMap.put("Oran", "Oran");
        cityMap.put("Konstantin", "Constantine");
        cityMap.put("Annaba", "Annaba");
        cityMap.put("Blida", "Blida");
        cityMap.put("Batna", "Batna");
        cityMap.put("Tlemsen", "Tlemcen");
        cityMap.put("Setif", "Setif");
        cityMap.put("Biskra", "Biskra");
        cityMap.put("El Oued", "El Oued");
        cityMap.put("Sidi Bel Abbes", "Sidi Bel Abbès");
        cityMap.put("Becaya", "Bejaïa");
        cityMap.put("Skikda", "Skikda");
        cityMap.put("Şlef", "Chlef");
        cityMap.put("Laqhouat", "Laghouat");
        cityMap.put("Ağcabədi", "Agjabadi");
        cityMap.put("Ağdam", "Agdam");
        cityMap.put("Ağdaş", "Agdash");
        cityMap.put("Ağdərə", "Agdere");
        cityMap.put("Ağstafa", "Agstafa");
        cityMap.put("Ağsu", "Agsu");
        cityMap.put("Astara", "Astara");
        cityMap.put("Babək", "Babek");
        cityMap.put("Bakı", "Baku");
        cityMap.put("Balakən", "Balakan");
        cityMap.put("Beyləqan", "Beylagan");
        cityMap.put("Bərdə", "Barda");
        cityMap.put("Biləsuvar", "Bilasuvar");
        cityMap.put("Cəbrayıl", "Jabrayil");
        cityMap.put("Cəlilabad", "Jalilabad");
        cityMap.put("Culfa", "Julfa");
        cityMap.put("Daşkəsən", "Dashkasan");
        cityMap.put("Dəliməmmədli", "Delimammadli");
        cityMap.put("Füzuli", "Fuzuli");
        cityMap.put("Gədəbəy", "Gadabay");
        cityMap.put("Gəncə", "Ganja");
        cityMap.put("Goranboy", "Goranboy");
        cityMap.put("Göyçay", "Goychay");
        cityMap.put("Göygöl", "Goygol");
        cityMap.put("Göytəpə", "Goytepe");
        cityMap.put("Hacıqabul", "Hajigabul");
        cityMap.put("Horadiz", "Horadiz");
        cityMap.put("Xaçmaz", "Khachmaz");
        cityMap.put("Xankəndi", "Khankendi");
        cityMap.put("Xızı", "Khizi");
        cityMap.put("Xocalı", "Khojali");
        cityMap.put("Xocavənd", "Khojavend");
        cityMap.put("Xırdalan", "Khirdalan");
        cityMap.put("Xudat", "Khudat");
        cityMap.put("İmişli", "Imishli");
        cityMap.put("İsmayıllı", "Ismayilli");
        cityMap.put("Kəlbəcər", "Kalbajar");
        cityMap.put("Kürdəmir", "Kurdamir");
        cityMap.put("Qax", "Gakh");
        cityMap.put("Qazax", "Gazakh");
        cityMap.put("Qəbələ", "Gabala");
        cityMap.put("Qobustan", "Gobustan");
        cityMap.put("Qovlar", "Govlar");
        cityMap.put("Quba", "Guba");
        cityMap.put("Qubadlı", "Gubadli");
        cityMap.put("Qusar", "Qusar");
        cityMap.put("Laçın", "Lachin");
        cityMap.put("Lerik", "Lerik");
        cityMap.put("Lənkəran", "Lankaran");
        cityMap.put("Liman", "Liman");
        cityMap.put("Masallı", "Masalli");
        cityMap.put("Mingəçevir", "Mingachevir");
        cityMap.put("Naftalan", "Naftalan");
        cityMap.put("Naxçıvan", "Nakhchivan");
        cityMap.put("Neftçala", "Neftchala");
        cityMap.put("Oğuz", "Oguz");
        cityMap.put("Ordubad", "Ordubad");
        cityMap.put("Saatlı", "Saatli");
        cityMap.put("Sabirabad", "Sabirabad");
        cityMap.put("Salyan", "Salyan");
        cityMap.put("Samux", "Samukh");
        cityMap.put("Siyəzən", "Siyazan");
        cityMap.put("Sumqayıt", "Sumgayit");
        cityMap.put("Şabran", "Shabran");
        cityMap.put("Şahbuz", "Shahbuz");
        cityMap.put("Şamaxı", "Shamakhi");
        cityMap.put("Şəki", "Shaki");
        cityMap.put("Şəmkir", "Shamkir");
        cityMap.put("Şərur", "Sharur");
        cityMap.put("Şirvan", "Shirvan");
        cityMap.put("Şuşa", "Shusha");
        cityMap.put("Tərtər", "Tartar");
        cityMap.put("Tovuz", "Tovuz");
        cityMap.put("Ucar", "Ujar");
        cityMap.put("Yardımlı", "Yardimli");
        cityMap.put("Yevlax", "Yevlakh");
        cityMap.put("Zaqatala", "Zagatala");
        cityMap.put("Zəngilan", "Zangilan");
        cityMap.put("Zərdab", "Zardab");
        cityMap.put("Adana", "Adana");
        cityMap.put("Adıyaman", "Adiyaman");
        cityMap.put("Afyonkarahisar", "Afyonkarahisar");
        cityMap.put("Ağrı", "Agri");
        cityMap.put("Aksaray", "Aksaray");
        cityMap.put("Amasya", "Amasya");
        cityMap.put("Ankara", "Ankara");
        cityMap.put("Antalya", "Antalya");
        cityMap.put("Ardahan", "Ardahan");
        cityMap.put("Artvin", "Artvin");
        cityMap.put("Aydın", "Aydin");
        cityMap.put("Balıkesir", "Balikesir");
        cityMap.put("Bartın", "Bartin");
        cityMap.put("Batman", "Batman");
        cityMap.put("Bayburt", "Bayburt");
        cityMap.put("Bilecik", "Bilecik");
        cityMap.put("Bingöl", "Bingol");
        cityMap.put("Bitlis", "Bitlis");
        cityMap.put("Bolu", "Bolu");
        cityMap.put("Burdur", "Burdur");
        cityMap.put("Bursa", "Bursa");
        cityMap.put("Çanakkale", "Çanakkale");
        cityMap.put("Çankırı", "Çankiri");
        cityMap.put("Çorum", "Çorum");
        cityMap.put("Denizli", "Denizli");
        cityMap.put("Diyarbakır", "Diyarbakir");
        cityMap.put("Düzce", "Düzce");
        cityMap.put("Edirne", "Edirne");
        cityMap.put("Elazığ", "Elazig");
        cityMap.put("Erzincan", "Erzincan");
        cityMap.put("Erzurum", "Erzurum");
        cityMap.put("Eskişehir", "Eskisehir");
        cityMap.put("Qaziantep", "Gaziantep");
        cityMap.put("Giresun", "Giresun");
        cityMap.put("Gümüşhane", "Gümüşhane");
        cityMap.put("Hakkari", "Hakkâri");
        cityMap.put("Hatay", "Hatay");
        cityMap.put("Iğdır", "Iğdir");
        cityMap.put("İsparta", "Isparta");
        cityMap.put("İstanbul", "Istanbul");
        cityMap.put("İzmir", "Izmir");
        cityMap.put("Kahramanmaraş", "Kahramanmaraş");
        cityMap.put("Karabük", "Karabük");
        cityMap.put("Karaman", "Karaman");
        cityMap.put("Kars", "Kars");
        cityMap.put("Kastamonu", "Kastamonu");
        cityMap.put("Kayseri", "Kayseri");
        cityMap.put("Kırıkkale", "Kirikkale");
        cityMap.put("Kırklareli", "Kirklareli");
        cityMap.put("Kırşehir", "Kirsehir");
        cityMap.put("Kilis", "Kilis");
        cityMap.put("Kocaeli", "Kocaeli");
        cityMap.put("Konya", "Konya");
        cityMap.put("Kütahya", "Kütahya");
        cityMap.put("Malatya", "Malatya");
        cityMap.put("Manisa", "Manisa");
        cityMap.put("Mardin", "Mardin");
        cityMap.put("Mersin", "Mersin");
        cityMap.put("Muğla", "Muğla");
        cityMap.put("Muş", "Muş");
        cityMap.put("Nevşehir", "Nevsehir");
        cityMap.put("Niğde", "Niğde");
        cityMap.put("Ordu", "Ordu");
        cityMap.put("Osmaniye", "Osmaniye");
        cityMap.put("Rize", "Rize");
        cityMap.put("Sakarya", "Sakarya");
        cityMap.put("Samsun", "Samsun");
        cityMap.put("Siirt", "Siirt");
        cityMap.put("Sinop", "Sinop");
        cityMap.put("Sivas", "Sivas");
        cityMap.put("Şanlıurfa", "Şanlıurfa");
        cityMap.put("Şırnak", "Şırnak");
        cityMap.put("Tekirdağ", "Tekirdağ");
        cityMap.put("Tokat", "Tokat");
        cityMap.put("Trabzon", "Trabzon");
        cityMap.put("Tunceli", "Tunceli");
        cityMap.put("Uşak", "Uşak");
        cityMap.put("Van", "Van");
        cityMap.put("Yalova", "Yalova");
        cityMap.put("Yozqat", "Yozgat");
        cityMap.put("Zonquldak", "Zonguldak");
        cityMap.put("Moskva", "Moscow");
        cityMap.put("Sankt-Peterburq", "Saint Petersburg");
        cityMap.put("Novosibirsk", "Novosibirsk");
        cityMap.put("Yekaterinburq", "Yekaterinburg");
        cityMap.put("Nijni Novqorod", "Nizhny Novgorod");
        cityMap.put("Samara", "Samara");
        cityMap.put("Omsk", "Omsk");
        cityMap.put("Kazan", "Kazan");
        cityMap.put("Çelyabinsk", "Chelyabinsk");
        cityMap.put("Rostov-na-Donu", "Rostov-on-Don");
        cityMap.put("Ufa", "Ufa");
        cityMap.put("Volqoqrad", "Volgograd");
        cityMap.put("Perm", "Perm");
        cityMap.put("Krasnoyarsk", "Krasnoyarsk");
        cityMap.put("Voronej", "Voronezh");
        cityMap.put("Saratov", "Saratov");
        cityMap.put("Krasnodar", "Krasnodar");
        cityMap.put("Tolyatti", "Tolyatti");
        cityMap.put("İjevsk", "Izhevsk");
        cityMap.put("Ulyanovsk", "Ulyanovsk");
        cityMap.put("Barnaul", "Barnaul");
        cityMap.put("Vladivostok", "Vladivostok");
        cityMap.put("Yaroslavl", "Yaroslavl");
        cityMap.put("İrkutsk", "Irkutsk");
        cityMap.put("Tümen", "Tyumen");
        cityMap.put("Maxaçqala", "Makhachkala");
        cityMap.put("Xabarovsk", "Khabarovsk");
        cityMap.put("Novokuznetsk", "Novokuznetsk");
        cityMap.put("Orenburq", "Orenburg");
        cityMap.put("Kemerovo", "Kemerovo");
        cityMap.put("Ryazan", "Ryazan");
        cityMap.put("Tomsk", "Tomsk");
        cityMap.put("Həştərxan", "Astrakhan");
        cityMap.put("Penza", "Penza");
        cityMap.put("Naberejnıe Çelnı", "Naberezhnye Chelny");
        cityMap.put("Lipetsk", "Lipetsk");
        cityMap.put("Tula", "Tula");
        cityMap.put("Kirov", "Kirov");
        cityMap.put("Çeboksarı", "Cheboksary");
        cityMap.put("Kalininqrad", "Kaliningrad");
        cityMap.put("Bryansk", "Bryansk");
        cityMap.put("Kursk", "Kursk");
        cityMap.put("İvanovo", "Ivanovo");
        cityMap.put("Maqnitoqorsk", "Magnitogorsk");
        cityMap.put("Ulan-Ude", "Ulan-Ude");
        cityMap.put("Tver", "Tver");
        cityMap.put("Stavropol", "Stavropol");
        cityMap.put("Nijni Tagil", "Nizhny Tagil");
        cityMap.put("Belqorod", "Belgorod");
        cityMap.put("Arxanqelsk", "Arkhangelsk");
        cityMap.put("Vladimir", "Vladimir");
        cityMap.put("Soçi", "Sochi");
        cityMap.put("Kurqan", "Kurgan");
        cityMap.put("Smolensk", "Smolensk");
        cityMap.put("Kaluqa", "Kaluga");
        cityMap.put("Çita", "Chita");
        cityMap.put("Oryol", "Oryol");
        cityMap.put("Voljski", "Volzhsky");
        cityMap.put("Çerepovets", "Cherepovets");
        cityMap.put("Vladiqafqaz", "Vladikavkaz");
        cityMap.put("Murmansk", "Murmansk");
        cityMap.put("Surqut", "Surgut");
        cityMap.put("Voloqda", "Vologda");
        cityMap.put("Saransk", "Saransk");
        cityMap.put("Tambov", "Tambov");
        cityMap.put("Sterlitamak", "Sterlitamak");
        cityMap.put("Qroznı", "Grozny");
        cityMap.put("Yakutsk", "Yakutsk");
        cityMap.put("Kostroma", "Kostroma");
        cityMap.put("Komsomolsk-na-Amure", "Komsomolsk-on-Amur");
        cityMap.put("Petrozavodsk", "Petrozavodsk");
        cityMap.put("Taqanroq", "Taganrog");
        cityMap.put("Nijnevartovsk", "Nizhnevartovsk");
        cityMap.put("Yoskar-Ola", "Yoshkar-Ola");
        cityMap.put("Bratsk", "Bratsk");
        cityMap.put("Novorossiysk", "Novorossiysk");
        cityMap.put("Dzerjinsk", "Dzerzhinsk");
        cityMap.put("Şaxtı", "Shakhty");
        cityMap.put("Nalçik", "Nalchik");
        cityMap.put("Orsk", "Orsk");
        cityMap.put("Sıktıvkar", "Syktyvkar");
        cityMap.put("Nijnekamsk", "Nizhnekamsk");
        cityMap.put("Anqarsk", "Angarsk");
        cityMap.put("Starıy Oskol", "Stary Oskol");
        cityMap.put("Berlin", "Berlin");
        cityMap.put("Hamburq", "Hamburg");
        cityMap.put("Münxen", "Munich");
        cityMap.put("Köln", "Cologne");
        cityMap.put("Frankfurt am Main", "Frankfurt am Main");
        cityMap.put("Ştutqart", "Stuttgart");
        cityMap.put("Düsseldorf", "Düsseldorf");
        cityMap.put("Dortmund", "Dortmund");
        cityMap.put("Essen", "Essen");
        cityMap.put("Leypsiq", "Leipzig");
        cityMap.put("Drezden", "Dresden");
        cityMap.put("Hannover", "Hannover");
        cityMap.put("Nürnberq", "Nuremberg");
        cityMap.put("Duisburq", "Duisburg");
        cityMap.put("Boxum", "Bochum");
        cityMap.put("Vuppertal", "Wuppertal");
        cityMap.put("Bilefeld", "Bielefeld");
        cityMap.put("Bonn", "Bonn");
        cityMap.put("Mannheim", "Mannheim");
        cityMap.put("Karlsrue", "Karlsruhe");
        cityMap.put("Visbaden", "Wiesbaden");
        cityMap.put("Münster", "Münster");
        cityMap.put("Auqsburq", "Augsburg");
        cityMap.put("Aaxen", "Aachen");
        cityMap.put("Mönchengladbach", "Mönchengladbach");
        cityMap.put("Gelzenkirxen", "Gelsenkirchen");
        cityMap.put("Braunşveyq", "Braunschweig");
        cityMap.put("Xemnits", "Chemnitz");
        cityMap.put("Kiel", "Kiel");
        cityMap.put("Maqdeburq", "Magdeburg");
        cityMap.put("Frayburq im Breyzqau", "Freiburg im Breisgau");
        cityMap.put("Krefeld", "Krefeld");
        cityMap.put("Lübek", "Lübeck");
        cityMap.put("Oberhauzen", "Oberhausen");
        cityMap.put("Erfurt", "Erfurt");
        cityMap.put("Maynts", "Mainz");
        cityMap.put("Rostok", "Rostock");
        cityMap.put("Kassel", "Kassel");
        cityMap.put("Hagen", "Hagen");
        cityMap.put("Saarbrücken", "Saarbrücken");
        cityMap.put("Hamm", "Hamm");
        cityMap.put("Mülheim an der Rur", "Mülheim an der Ruhr");
        cityMap.put("Potsdam", "Potsdam");
        cityMap.put("Ludviqshafen am Reyn", "Ludwigshafen am Rhein");
        cityMap.put("Oldenburq", "Oldenburg");
        cityMap.put("Leverkuzen", "Leverkusen");
        cityMap.put("Osnabrük", "Osnabrück");
        cityMap.put("Solingen", "Solingen");
        cityMap.put("Heydelberq", "Heidelberg");
        cityMap.put("Herne", "Herne");
        cityMap.put("Neuss", "Neuss");
        cityMap.put("Darmştadt", "Darmstadt");
        cityMap.put("Paderborn", "Paderborn");
        cityMap.put("Reqensburq", "Regensburg");
        cityMap.put("İnqolştadt", "Ingolstadt");
        cityMap.put("Vürtsburq", "Würzburg");
        cityMap.put("Volfsburq", "Wolfsburg");
        cityMap.put("Ulm", "Ulm");
        cityMap.put("Offenbax am Main", "Offenbach am Main");
        cityMap.put("Heylbronn", "Heilbronn");
        cityMap.put("Pfortsheim", "Pforzheim");
        cityMap.put("Göttinqen", "Göttingen");
        cityMap.put("Bottrop", "Bottrop");
        cityMap.put("Trier", "Trier");
        cityMap.put("Reklinqhauzen", "Recklinghausen");
        cityMap.put("Roytlingen", "Reutlingen");
        cityMap.put("Bremerhaven", "Bremerhaven");
        cityMap.put("Koblents", "Koblenz");
        cityMap.put("Berqiş Qladbax", "Bergisch Gladbach");
        cityMap.put("Yena", "Jena");
        cityMap.put("Remşeyd", "Remscheid");
        cityMap.put("Erlenqen", "Erlangen");
        cityMap.put("Moers", "Moers");
        cityMap.put("Ziqen", "Siegen");
        cityMap.put("Hildeshaym", "Hildesheim");
        cityMap.put("Salzgitter", "Salzgitter");
        cityMap.put("Kottbus", "Cottbus");
        cityMap.put("Kayzerslautern", "Kaiserslautern");
        cityMap.put("Gera", "Gera");
        cityMap.put("Vitten", "Witten");
        cityMap.put("İzerlon", "Iserlohn");
        cityMap.put("Hanau", "Hanau");
        cityMap.put("Dessau-Rosslau", "Dessau-Roßlau");
        cityMap.put("Velbert", "Velbert");
        cityMap.put("Düüren", "Düren");
        cityMap.put("Ratinqen", "Ratingen");
        cityMap.put("Lüdənşeyd", "Lüdenscheid");
        cityMap.put("Marl", "Marl");
        cityMap.put("Flensburq", "Flensburg");
        cityMap.put("Neumünster", "Neumünster");
        cityMap.put("Qladbek", "Gladbeck");
        cityMap.put("Kamen", "Kamen");
        cityMap.put("Gütersloh", "Gütersloh");
        cityMap.put("Vorms", "Worms");
        cityMap.put("Ravensburq", "Ravensburg");
        cityMap.put("Landshut", "Landshut");
        cityMap.put("Ludviqsburq", "Ludwigsburg");
        cityMap.put("Aşaffenburq", "Aschaffenburg");
        cityMap.put("Bamberg", "Bamberg");
        cityMap.put("Şverin", "Schwerin");
        cityMap.put("Nyu York Siti", "New York City");
        cityMap.put("Los Anceles", "Los Angeles");
        cityMap.put("Çikaqo", "Chicago");
        cityMap.put("Houston", "Houston");
        cityMap.put("Feniks", "Phoenix");
        cityMap.put("Filadelfiya", "Philadelphia");
        cityMap.put("San Antonio", "San Antonio");
        cityMap.put("San Dieqo", "San Diego");
        cityMap.put("Dallas", "Dallas");
        cityMap.put("San Jose", "San Jose");
        cityMap.put("Ostin", "Austin");
        cityMap.put("Ceksonvil", "Jacksonville");
        cityMap.put("Fort Vort", "Fort Worth");
        cityMap.put("Kolumbus", "Columbus");
        cityMap.put("Şarlot", "Charlotte");
        cityMap.put("San Fransisko", "San Francisco");
        cityMap.put("İndianapolis", "Indianapolis");
        cityMap.put("Sietl", "Seattle");
    }

    //Olkeni ingilise cevirir
    public static String getTranslation(String word) {
        return countryMap.get(word);
    }

    //Seherin Azerbaycanca olani Ingilise cevir
    public static String getCityTranslation(String word){
        if (cityMap.get(word) == null){
            throw new InvalidInputException("City isn't available in our platform right now");
        } else {
            return cityMap.get(word);
        }
    }
    //Seherin ingilisce olani azerbaycanca
    public static String getCityInAzerbajani(String word){
        if(word !=null){
            for(Map.Entry<String, String> entry: cityMap.entrySet() ){
                if(entry.getValue().equals(word)){
                    return entry.getKey();
                }
            }
            throw new InvalidInputException("City isn't available in our platform right now");
        } else {
            throw new InvalidInputException("City name cannnot be null");
        }
    }

    public static String getAzerbaijani(String word) {
        if (word != null) {
            for (Map.Entry<String, String> entry : countryMap.entrySet()) {
                if (entry.getValue().equals(word)) {
                    return entry.getKey();
                }
            }
        } else {
            throw new InvalidInputException("INPUT_IS_EMPTY");
        }

        throw new InvalidInputException("THERE_IS_NOT_COUNTRY");
    }


    public static String getLink(String link) {
        String inEnglish = link.toLowerCase().replaceAll("ə", "e")
                .replaceAll("ğ", "g")
                .replaceAll("ı", "i")
                .replaceAll("ç", "c")
                .replaceAll("ö", "o")
                .replaceAll("ü", "u")
                .replaceAll("q", "g")
                .replaceAll(" ", "-");
        StringBuilder suffix = new StringBuilder("-");
        Random ran = new Random();
        for (int i = 0; i < 15; i++) {
            int index = ran.nextInt(0, ALPHANUMERICS.length());
            if (ran.nextInt(1000) % 2 == 0) {
                suffix.append(Character.toLowerCase(ALPHANUMERICS.charAt(index)));
            } else {
                suffix.append(ALPHANUMERICS.charAt(index));
            }
        }
        return inEnglish + suffix;

    }
}
